# Generated by Django 5.2.3 on 2025-07-01 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('singer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('kuwo_id', models.IntegerField(default=-1, primary_key=True, serialize=False, verbose_name='kuwo_id')),
                ('name', models.CharField(default='', max_length=100, verbose_name='name')),
                ('image', models.ImageField(default='', upload_to='', verbose_name='picture')),
                ('original_image_url', models.URLField(blank=True, max_length=1024, null=True, verbose_name='original image URL')),
                ('original_url', models.URLField(default='', unique=True, verbose_name='original URL')),
                ('release_date', models.CharField(blank=True, max_length=50, null=True, verbose_name='release date')),
                ('duration', models.IntegerField(default=-1, verbose_name='seconds of the song')),
                ('album_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='album name')),
                ('lyrics', models.TextField(blank=True, max_length=5000, null=True, verbose_name='lyrics')),
                ('comments', models.JSONField(blank=True, default=list, help_text='list of comments')),
                ('singer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='songs', to='singer.singer', verbose_name='singer')),
            ],
        ),
    ]
