# Generated by Django 5.2.3 on 2025-07-01 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('kuwo_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='kuwo_id')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='name')),
                ('image', models.ImageField(upload_to='', verbose_name='picture')),
                ('info', models.TextField(blank=True, null=True, verbose_name='information')),
                ('original_image_url', models.URLField(blank=True, max_length=1024, verbose_name='original image URL')),
                ('original_url', models.URLField(unique=True, verbose_name='original URL')),
                ('fan_num', models.IntegerField(default=0, verbose_name='number of fans')),
                ('album_num', models.IntegerField(default=0, verbose_name='number of albums')),
                ('mv_num', models.IntegerField(default=0, verbose_name='number of MVs')),
                ('music_num', models.IntegerField(default=0, verbose_name='number of musics')),
                ('alias', models.CharField(blank=True, max_length=50, null=True, verbose_name='another name')),
                ('birthday', models.CharField(blank=True, max_length=50, null=True, verbose_name='birthday')),
                ('birthplace', models.CharField(blank=True, max_length=50, null=True, verbose_name='birthplace')),
                ('region', models.CharField(blank=True, max_length=50, null=True, verbose_name='region')),
                ('gender', models.CharField(blank=True, max_length=10, null=True, verbose_name='gender')),
                ('weight', models.CharField(blank=True, max_length=20, null=True, verbose_name='weight')),
                ('height', models.CharField(blank=True, max_length=20, null=True, verbose_name='height')),
                ('language', models.CharField(blank=True, max_length=50, null=True, verbose_name='language')),
                ('constellation', models.CharField(blank=True, max_length=50, null=True, verbose_name='constellation')),
            ],
        ),
    ]
