# Generated by Django 5.2.3 on 2025-07-04 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='singer',
            name='image',
            field=models.ImageField(upload_to='Singer', verbose_name='picture'),
        ),
    ]
