# Generated by Django 5.2.3 on 2025-06-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('singer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='singer',
            name='original_image_url',
            field=models.URLField(blank=True, max_length=1024, verbose_name='original image URL'),
        ),
    ]
